/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cl.duoc.evaluacion3.Views;

import cl.duoc.evaluacion3.DTO.MovieDTO;
import cl.duoc.evaluacion3.Services.IMovie;
import cl.duoc.evaluacion3.ServicesImpls.MovieService;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class AgregarViews extends javax.swing.JInternalFrame {
    
    private static IMovie servicio ;
    public AgregarViews() {
        initComponents();
        if (servicio == null) {
            servicio = new MovieService();         
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulotexto = new javax.swing.JLabel();
        TxtTitulo = new javax.swing.JTextField();
        Duraciontexto = new javax.swing.JLabel();
        Directortexto = new javax.swing.JLabel();
        Aniotexto = new javax.swing.JLabel();
        Generotexto = new javax.swing.JLabel();
        SeleccionGenero = new javax.swing.JComboBox<>();
        TxtDuracion = new javax.swing.JTextField();
        TxtDirector = new javax.swing.JTextField();
        TxtAnio = new javax.swing.JTextField();
        BGuardar = new javax.swing.JButton();
        BLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Pelicula");

        Titulotexto.setText("Titulo");

        TxtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTituloActionPerformed(evt);
            }
        });

        Duraciontexto.setText("Duracion");

        Directortexto.setText("Director");

        Aniotexto.setText("Año");

        Generotexto.setText("Genero");

        SeleccionGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione Genero -", "Drama", "Comedia", "Accion", "Romance ", "Suspenso", "Terror" }));
        SeleccionGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionGeneroActionPerformed(evt);
            }
        });

        TxtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDuracionActionPerformed(evt);
            }
        });

        TxtDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDirectorActionPerformed(evt);
            }
        });

        BGuardar.setText("Guardar");
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });

        BLimpiar.setText("Limpiar");
        BLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        TxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BLimpiar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Generotexto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(SeleccionGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Aniotexto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Directortexto))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtDirector)
                                .addComponent(TxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Duraciontexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Titulotexto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtTitulo)
                                .addComponent(TxtDuracion)
                                .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulotexto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Duraciontexto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Directortexto)
                    .addComponent(TxtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aniotexto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Generotexto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void TxtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTituloActionPerformed

    private void SeleccionGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionGeneroActionPerformed

    private void TxtDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDirectorActionPerformed

    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed

        int id = 0;
        String titulo = "";
        int duracion = -1;
        String director = "";
        int anio = -1;
        String genero = null;

        try {
            if (!TxtID.getText().isEmpty()) {
                id = Integer.parseInt(TxtID.getText());

                if (id <= 0) {
                    JOptionPane.showMessageDialog(this, "El ID debe ser un valor mayor a 0");
                    return;
                }
            }
            if (!TxtAnio.getText().isEmpty()) {
                anio = Integer.parseInt(TxtAnio.getText());
                if (anio <= 0) {
                    JOptionPane.showMessageDialog(this, "El Año debe ser un valor mayor a 0");
                    return;
                }
            }
            if (!TxtDuracion.getText().isEmpty()) {
                duracion = Integer.parseInt(TxtDuracion.getText());
                if (duracion <= 0) {
                    JOptionPane.showMessageDialog(this, "La Duracion debe ser un valor mayor a 0");
                    return;
                }
            }
            if (!TxtDirector.getText().isEmpty()) {
                director = TxtDirector.getText();
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese el campo Director correctamente");
                return;
            }
            if (!TxtTitulo.getText().isEmpty()) {
                titulo = TxtTitulo.getText();
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese el campo Título correctamente");
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese los campos numéricos correctamente");
            return;
        }
        if (SeleccionGenero.getSelectedIndex() > 0) {
            genero = SeleccionGenero.getSelectedItem().toString();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un género");
            return;
        }
        MovieDTO m = new MovieDTO(titulo, director, genero, id, anio, duracion);
        boolean v = servicio.Guardar(m);

        if (!v) {
            JOptionPane.showMessageDialog(this, "El ID ya se encuentra registrado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Película guardada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
 
    }//GEN-LAST:event_BGuardarActionPerformed

    private void BLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarActionPerformed
        // TODO add your handling code here:
        TxtID.setText("");
        TxtTitulo.setText("");
        TxtAnio.setText("");
        TxtDirector.setText("");
        TxtDuracion.setText("");
        SeleccionGenero.setSelectedIndex(0);
    }//GEN-LAST:event_BLimpiarActionPerformed

    private void TxtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDuracionActionPerformed

    private void TxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aniotexto;
    private javax.swing.JButton BGuardar;
    private javax.swing.JButton BLimpiar;
    private javax.swing.JLabel Directortexto;
    private javax.swing.JLabel Duraciontexto;
    private javax.swing.JLabel Generotexto;
    private javax.swing.JComboBox<String> SeleccionGenero;
    private javax.swing.JLabel Titulotexto;
    private javax.swing.JTextField TxtAnio;
    private javax.swing.JTextField TxtDirector;
    private javax.swing.JTextField TxtDuracion;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtTitulo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
