/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cl.duoc.evaluacion3.Views;


import cl.duoc.evaluacion3.DTO.MovieDTO;
import cl.duoc.evaluacion3.Services.IMovie;
import cl.duoc.evaluacion3.ServicesImpls.MovieService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class EliminarViews extends javax.swing.JInternalFrame {

    private static IMovie servicio ;
    public EliminarViews() {
        initComponents();
        if (servicio == null) {
            servicio = new MovieService();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BEliminarPelicula = new javax.swing.JButton();
        NombrePelicula = new javax.swing.JLabel();
        BLimpiar = new javax.swing.JButton();
        TxtBusquedaPelicula = new javax.swing.JTextField();
        BBuscarPelicula = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Eliminar Pelicula");

        BEliminarPelicula.setText("Eliminar Pelicula");
        BEliminarPelicula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarPeliculaActionPerformed(evt);
            }
        });

        NombrePelicula.setText("Nombre de la Pelicula");

        BLimpiar.setText("Limpiar");
        BLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarActionPerformed(evt);
            }
        });

        TxtBusquedaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBusquedaPeliculaActionPerformed(evt);
            }
        });

        BBuscarPelicula.setText("Buscar Pelicula");
        BBuscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BBuscarPelicula)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NombrePelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtBusquedaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BEliminarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBusquedaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBuscarPelicula)
                    .addComponent(BLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(BEliminarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarPeliculaActionPerformed
        // TODO add your handling code here:
        boolean peliculaEncontrada = false;
        titulo = TxtBusquedaPelicula.getText();
        if(!titulo.isEmpty()){
            for (MovieDTO m : lista) {
                if (titulo.equals(m.getTitulo())) {
                    id = m.getID();
                    peliculaEncontrada = true;
                    break;  
                }
            }
           try {
               if(!peliculaEncontrada && !titulo.isEmpty() ){
                    JOptionPane.showMessageDialog(null,"No existe ninguna pelicula con ese titulo","Error", JOptionPane.ERROR_MESSAGE);
                }else{
                   int eliminar = JOptionPane.showConfirmDialog(null,"Estas seguro que deseas eliminar esta pelicula","Confirmacion",JOptionPane.YES_NO_OPTION);
                    if (eliminar == JOptionPane.YES_OPTION){
                       JOptionPane.showMessageDialog(null, "Película eliminada de la base de datos", titulo.toString() , JOptionPane.INFORMATION_MESSAGE);
                     servicio.Eliminar(id); 
                     servicio.listar();
                    } else {
                        JOptionPane.showConfirmDialog(null, "Operacion cancelada", "Cancelar", JOptionPane.PLAIN_MESSAGE);
                    }     
                    }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al eliminar la película " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese un titulo para buscar", "Campo titulo vacio", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BEliminarPeliculaActionPerformed

    private void BLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarActionPerformed
    // TODO add your handling code here:
    TxtBusquedaPelicula.setText("");
    }//GEN-LAST:event_BLimpiarActionPerformed

    private void TxtBusquedaPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBusquedaPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBusquedaPeliculaActionPerformed
    List<MovieDTO> lista = new ArrayList<>();
    static String titulo;
    static int id;
    private void BBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarPeliculaActionPerformed
        // TODO add your handling code here:
        titulo = TxtBusquedaPelicula.getText();
        servicio.BuscarTitulo(titulo);
        lista = servicio.BuscarTitulo(titulo);
        boolean peliculaEncontrada = false;
        
        for (MovieDTO m : lista) {
            if (titulo.equals(m.getTitulo())) {
                id = m.getID();
                peliculaEncontrada = true;
                break;  
            }
        }

        if (!peliculaEncontrada) {
            JOptionPane.showMessageDialog(null, "Pelicula no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }else{
            JOptionPane.showMessageDialog(null,"Pelicula Encontrada ", "Exito",JOptionPane.PLAIN_MESSAGE);
        }

    }//GEN-LAST:event_BBuscarPeliculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscarPelicula;
    private javax.swing.JButton BEliminarPelicula;
    private javax.swing.JButton BLimpiar;
    private javax.swing.JLabel NombrePelicula;
    private javax.swing.JTextField TxtBusquedaPelicula;
    // End of variables declaration//GEN-END:variables
}
