/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.duoc.evaluacion3;

import cl.duoc.evaluacion3.Views.AgregarViews;
import cl.duoc.evaluacion3.Views.EliminarViews;
import cl.duoc.evaluacion3.Views.ListarViews;
import cl.duoc.evaluacion3.Views.ModificarViews;
import javax.swing.JInternalFrame;


/**
 *
 * @author Marco
 */
public class Evaluacion3 extends javax.swing.JFrame {

    /**
     * Creates new form Evaluacion3
     */
    public Evaluacion3() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        Escritorio = new javax.swing.JDesktopPane();
        EscritorioMenu = new javax.swing.JMenuBar();
        Opciones = new javax.swing.JMenu();
        AgregarPelicula = new javax.swing.JMenuItem();
        ModificarPelicula = new javax.swing.JMenuItem();
        EliminarPelicula = new javax.swing.JMenuItem();
        ListadoPeliculas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        Opciones.setText("Pelicula");

        AgregarPelicula.setText("Agregar");
        AgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPeliculaActionPerformed(evt);
            }
        });
        Opciones.add(AgregarPelicula);

        ModificarPelicula.setText("Modificar");
        ModificarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPeliculaActionPerformed(evt);
            }
        });
        Opciones.add(ModificarPelicula);

        EliminarPelicula.setText("Eliminar");
        EliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPeliculaActionPerformed(evt);
            }
        });
        Opciones.add(EliminarPelicula);

        ListadoPeliculas.setText("Listado");
        ListadoPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoPeliculasActionPerformed(evt);
            }
        });
        Opciones.add(ListadoPeliculas);

        EscritorioMenu.add(Opciones);

        setJMenuBar(EscritorioMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void AgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPeliculaActionPerformed
        // TODO add your handling code here:
       JInternalFrame AgregarViews = new AgregarViews();
       Escritorio.add(AgregarViews);
       AgregarViews.setVisible(true);
    }//GEN-LAST:event_AgregarPeliculaActionPerformed
    
    private void ModificarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPeliculaActionPerformed
        // TODO add your handling code here:
        JInternalFrame ModificarViews = new ModificarViews();
        Escritorio.add(ModificarViews);
        ModificarViews.setVisible(true);
    }//GEN-LAST:event_ModificarPeliculaActionPerformed
    
    private void ListadoPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoPeliculasActionPerformed
        // TODO add your handling code here:
        ListarViews ListarViews = new ListarViews();
        Escritorio.add(ListarViews);
        ListarViews.setVisible(true);
    }//GEN-LAST:event_ListadoPeliculasActionPerformed
    
    private void EliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPeliculaActionPerformed
        // TODO add your handling code here:
        JInternalFrame Eliminar = new EliminarViews();
        Escritorio.add(Eliminar);
        Eliminar.setVisible(true);
    }//GEN-LAST:event_EliminarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluacion3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarPelicula;
    private javax.swing.JMenuItem EliminarPelicula;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar EscritorioMenu;
    private javax.swing.JMenuItem ListadoPeliculas;
    private javax.swing.JMenuItem ModificarPelicula;
    private javax.swing.JMenu Opciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
